import {
  ZERO_NUTRITION,
  type MenuItem,
  type ModifierOption,
  type Nutrition,
} from '@healthyapp/shared';

/**
 * Sample menu for one Lahore store. Placeholder until the menu comes from Supabase (per store,
 * per the user's address); only this file changes when it does.
 *
 * Numbers are consistent with Atwater factors (4 kcal/g protein and carbs, 9 kcal/g fat), and
 * sugar is total sugar as declared on the label.
 */
export const SAMPLE_STORE_ID = 'lhr-gulberg';

const n = (
  kcal: number,
  proteinG: number,
  carbsG: number,
  fatG: number,
  sugarG: number,
): Nutrition => ({
  kcal,
  proteinG,
  carbsG,
  fatG,
  sugarG,
});

const keep = (id: string, name: string, isDefault = false): ModifierOption => ({
  id,
  name,
  delta: ZERO_NUTRITION,
  priceDelta: 0,
  available: true,
  isDefault,
});

const avocado: ModifierOption = {
  id: 'avocado',
  name: 'Avocado (50g)',
  delta: n(80, 1, 4, 7, 0),
  priceDelta: 180,
  available: true,
};

const SWEETNESS = {
  id: 'sweetness',
  name: 'Sweetness',
  type: 'single' as const,
  options: [
    keep('none', 'No sweetener', true),
    {
      id: 'dates',
      name: 'Dates (2)',
      delta: n(46, 0.4, 12, 0, 11),
      priceDelta: 50,
      available: true,
    },
    {
      id: 'honey',
      name: 'Honey (1 tsp)',
      delta: n(21, 0, 6, 0, 6),
      priceDelta: 0,
      available: true,
    },
  ],
};

const SAMPLE_MENU: MenuItem[] = [
  {
    id: 'chicken-bowl',
    storeId: SAMPLE_STORE_ID,
    name: 'Grilled Chicken Bowl',
    category: 'bowls',
    description: 'Smoky chicken, brown rice, chickpeas and crisp greens.',
    basePrice: 890,
    base: n(610, 42, 68, 18, 4),
    fibreG: 9,
    badge: 'calculated',
    ingredients: [
      { name: 'Grilled chicken', grams: 150 },
      { name: 'Brown rice', grams: 150 },
      { name: 'Chickpeas', grams: 60 },
      { name: 'Cucumber', grams: 50 },
      { name: 'Mixed greens', grams: 40 },
      { name: 'Yogurt sauce', grams: 40 },
    ],
    allergens: ['milk'],
    kitchenAlsoHandles: ['wheat', 'egg', 'soy', 'peanut', 'tree_nut', 'sesame'],
    dietTags: ['eggless'],
    available: true,
    modifierGroups: [
      {
        id: 'base',
        name: 'Base',
        type: 'single',
        options: [
          keep('brown-rice', 'Brown rice', true),
          {
            id: 'quinoa',
            name: 'Quinoa',
            delta: n(10, 2, -4, 2, 0),
            priceDelta: 120,
            available: true,
          },
          {
            id: 'greens',
            name: 'Extra greens instead of rice',
            delta: n(-150, -3, -33, -1, 1),
            priceDelta: 0,
            available: true,
          },
        ],
      },
      {
        id: 'chicken',
        name: 'Chicken',
        type: 'stepper',
        unit: 'portion',
        min: 1,
        max: 4,
        defaultCount: 2,
        option: {
          id: 'chicken-portion',
          name: 'Chicken (75g)',
          delta: n(120, 23, 0, 3, 0),
          priceDelta: 250,
          available: true,
        },
      },
      {
        id: 'addons',
        name: 'Add-ons',
        type: 'multi',
        max: 3,
        options: [
          avocado,
          {
            id: 'egg',
            name: 'Boiled egg',
            delta: n(78, 6, 1, 5, 0),
            priceDelta: 80,
            allergens: ['egg'],
            available: true,
          },
          {
            id: 'feta',
            name: 'Feta (30g)',
            delta: n(75, 4, 1, 6, 0),
            priceDelta: 150,
            allergens: ['milk'],
            available: false,
          },
        ],
      },
      {
        id: 'remove',
        name: 'Leave out',
        type: 'remove',
        options: [
          {
            id: 'no-sauce',
            name: 'Yogurt sauce',
            delta: n(-60, -2, -3, -4.5, -2),
            priceDelta: 0,
            available: true,
          },
          {
            id: 'no-chickpeas',
            name: 'Chickpeas',
            delta: n(-100, -5, -16, -1.5, -1),
            priceDelta: 0,
            available: true,
          },
        ],
      },
    ],
  },
  {
    id: 'karahi-bowl',
    storeId: SAMPLE_STORE_ID,
    name: 'Chicken Karahi, Less Oil',
    category: 'bowls',
    description: 'Desi karahi made lighter: tomato, ginger, green chilli and very little oil.',
    basePrice: 950,
    base: n(550, 45, 55, 16, 6),
    fibreG: 7,
    badge: 'verified',
    ingredients: [
      { name: 'Chicken breast', grams: 160 },
      { name: 'Tomato and onion masala', grams: 120 },
      { name: 'Brown rice', grams: 150 },
      { name: 'Canola oil', grams: 8 },
      { name: 'Yogurt marinade', grams: 20 },
    ],
    allergens: ['milk'],
    kitchenAlsoHandles: ['wheat', 'egg', 'soy', 'peanut', 'tree_nut', 'sesame'],
    dietTags: ['eggless'],
    available: true,
    modifierGroups: [
      {
        id: 'side',
        name: 'Served with',
        type: 'single',
        options: [
          keep('brown-rice', 'Brown rice', true),
          {
            id: 'roti',
            name: '2 whole-wheat roti',
            delta: n(60, 5, 8, 1, 0),
            priceDelta: 0,
            allergens: ['wheat'],
            available: true,
          },
          {
            id: 'no-side',
            name: 'No rice or roti',
            delta: n(-165, -4, -35, -1, 0),
            priceDelta: -100,
            available: true,
          },
        ],
      },
      {
        id: 'spice',
        name: 'Spice level',
        type: 'single',
        options: [keep('mild', 'Mild'), keep('medium', 'Medium', true), keep('hot', 'Hot')],
      },
      {
        id: 'addons',
        name: 'Add-ons',
        type: 'multi',
        max: 2,
        options: [
          {
            id: 'raita',
            name: 'Cucumber raita',
            delta: n(70, 4, 5, 3.5, 5),
            priceDelta: 100,
            allergens: ['milk'],
            available: true,
          },
          {
            id: 'salad',
            name: 'Kachumber salad',
            delta: n(35, 1, 7, 0.3, 4),
            priceDelta: 100,
            available: true,
          },
        ],
      },
    ],
  },
  {
    id: 'falafel-bowl',
    storeId: SAMPLE_STORE_ID,
    name: 'The Falafel Bowl',
    category: 'bowls',
    description: 'Herby baked falafel, seasonal vegetables and tahini.',
    basePrice: 790,
    base: n(540, 21, 62, 23, 6),
    fibreG: 14,
    badge: 'calculated',
    ingredients: [
      { name: 'Baked falafel', grams: 120 },
      { name: 'Mixed greens', grams: 60 },
      { name: 'Chickpeas', grams: 60 },
      { name: 'Cucumber and tomato', grams: 80 },
      { name: 'Tahini', grams: 20 },
    ],
    allergens: ['sesame'],
    kitchenAlsoHandles: ['milk', 'wheat', 'egg', 'soy', 'peanut', 'tree_nut'],
    dietTags: ['vegetarian', 'eggless', 'dairy_free'],
    available: true,
    modifierGroups: [
      {
        id: 'addons',
        name: 'Add-ons',
        type: 'multi',
        max: 2,
        options: [
          {
            id: 'falafel',
            name: 'Extra falafel (2)',
            delta: n(170, 7, 16, 9, 1),
            priceDelta: 200,
            available: true,
          },
          {
            id: 'hummus',
            name: 'Hummus (40g)',
            delta: n(100, 4, 8, 6, 0),
            priceDelta: 150,
            allergens: ['sesame'],
            available: true,
          },
          avocado,
        ],
      },
      {
        id: 'remove',
        name: 'Leave out',
        type: 'remove',
        options: [
          {
            id: 'no-tahini',
            name: 'Tahini',
            delta: n(-90, -3, -3, -8, 0),
            priceDelta: 0,
            available: true,
          },
        ],
      },
    ],
  },
  {
    id: 'daal-chawal',
    storeId: SAMPLE_STORE_ID,
    name: 'Daal Chawal, Brown Rice',
    category: 'bowls',
    description: 'Yellow daal with a light tarka, brown rice and kachumber.',
    basePrice: 590,
    base: n(470, 18, 78, 9, 4),
    fibreG: 13,
    badge: 'verified',
    ingredients: [
      { name: 'Moong and masoor daal', grams: 200 },
      { name: 'Brown rice', grams: 150 },
      { name: 'Kachumber salad', grams: 60 },
      { name: 'Canola oil tarka', grams: 6 },
    ],
    allergens: [],
    kitchenAlsoHandles: ['milk', 'wheat', 'egg', 'soy', 'peanut', 'tree_nut', 'sesame'],
    dietTags: ['vegetarian', 'eggless', 'dairy_free'],
    available: true,
    modifierGroups: [
      {
        id: 'addons',
        name: 'Add-ons',
        type: 'multi',
        max: 2,
        options: [
          {
            id: 'raita',
            name: 'Cucumber raita',
            delta: n(70, 4, 5, 3.5, 5),
            priceDelta: 100,
            allergens: ['milk'],
            available: true,
          },
          {
            id: 'egg',
            name: 'Boiled egg',
            delta: n(78, 6, 1, 5, 0),
            priceDelta: 80,
            allergens: ['egg'],
            available: true,
          },
        ],
      },
    ],
  },
  {
    id: 'egg-white-omelette',
    storeId: SAMPLE_STORE_ID,
    name: 'Masala Egg-White Omelette',
    category: 'breakfast',
    description: 'Egg whites with onion, tomato and green chilli, on whole-wheat toast.',
    basePrice: 520,
    base: n(320, 30, 28, 9, 3),
    fibreG: 5,
    badge: 'calculated',
    ingredients: [
      { name: 'Egg whites', grams: 200 },
      { name: 'Onion, tomato, chilli', grams: 60 },
      { name: 'Whole-wheat toast', grams: 60 },
      { name: 'Olive oil', grams: 5 },
    ],
    allergens: ['egg', 'wheat'],
    kitchenAlsoHandles: ['milk', 'soy', 'peanut', 'tree_nut', 'sesame'],
    dietTags: ['vegetarian', 'dairy_free'],
    available: true,
    modifierGroups: [
      {
        id: 'addons',
        name: 'Add-ons',
        type: 'multi',
        max: 2,
        options: [
          avocado,
          {
            id: 'whole-egg',
            name: 'Add a whole egg',
            delta: n(72, 6, 0.4, 5, 0),
            priceDelta: 60,
            allergens: ['egg'],
            available: true,
          },
        ],
      },
      {
        id: 'remove',
        name: 'Leave out',
        type: 'remove',
        options: [
          {
            id: 'no-toast',
            name: 'Toast',
            delta: n(-140, -6, -24, -2, -2),
            priceDelta: 0,
            available: true,
          },
        ],
      },
    ],
  },
  {
    id: 'berry-parfait',
    storeId: SAMPLE_STORE_ID,
    name: 'Berry Yogurt Parfait',
    category: 'breakfast',
    description: 'Creamy low-fat yogurt, berries and crunchy oat granola.',
    basePrice: 590,
    base: n(340, 19, 43, 10, 18),
    fibreG: 5,
    badge: 'estimated',
    ingredients: [
      { name: 'Low-fat yogurt', grams: 200 },
      { name: 'Mixed berries', grams: 80 },
      { name: 'Oat granola', grams: 35 },
    ],
    allergens: ['milk', 'wheat', 'tree_nut'],
    kitchenAlsoHandles: ['egg', 'soy', 'peanut', 'sesame'],
    dietTags: ['vegetarian', 'eggless', 'no_added_sugar'],
    available: true,
    modifierGroups: [
      SWEETNESS,
      {
        id: 'remove',
        name: 'Leave out',
        type: 'remove',
        options: [
          {
            id: 'no-granola',
            name: 'Granola',
            delta: n(-150, -4, -22, -5, -6),
            priceDelta: 0,
            available: true,
          },
        ],
      },
    ],
  },
  {
    id: 'pb-banana-shake',
    storeId: SAMPLE_STORE_ID,
    name: 'Peanut Butter Banana Shake',
    category: 'drinks',
    description: 'Banana, peanut butter and low-fat milk. Add whey for a post-workout shake.',
    basePrice: 650,
    base: n(400, 20, 52, 12, 34),
    fibreG: 4,
    badge: 'calculated',
    ingredients: [
      { name: 'Low-fat milk', grams: 300 },
      { name: 'Banana', grams: 120 },
      { name: 'Peanut butter', grams: 15 },
    ],
    allergens: ['milk', 'peanut'],
    kitchenAlsoHandles: ['wheat', 'egg', 'soy', 'tree_nut', 'sesame'],
    dietTags: ['vegetarian', 'eggless', 'no_added_sugar'],
    available: true,
    modifierGroups: [
      {
        id: 'milk',
        name: 'Milk',
        type: 'single',
        options: [
          keep('low-fat', 'Low-fat milk', true),
          {
            id: 'whole',
            name: 'Whole milk',
            delta: n(45, 0, 0, 5, 0),
            priceDelta: 0,
            available: true,
          },
          {
            id: 'almond',
            name: 'Unsweetened almond milk',
            delta: n(-90, -8.5, -13.5, -1, -15),
            priceDelta: 120,
            allergens: ['tree_nut'],
            available: true,
          },
          {
            id: 'oat',
            name: 'Oat milk',
            delta: n(0, -7, 6, 0, -6),
            priceDelta: 120,
            available: false,
          },
        ],
      },
      {
        id: 'whey',
        name: 'Whey protein',
        type: 'stepper',
        unit: 'scoop',
        min: 0,
        max: 2,
        defaultCount: 0,
        option: {
          id: 'whey-scoop',
          name: 'Whey (30g scoop)',
          delta: n(120, 24, 3, 1.5, 2),
          priceDelta: 200,
          allergens: ['milk'],
          available: true,
        },
      },
      SWEETNESS,
    ],
  },
  {
    id: 'mango-lassi',
    storeId: SAMPLE_STORE_ID,
    name: 'Mango Lassi, No Added Sugar',
    category: 'drinks',
    description: 'Low-fat yogurt and ripe mango, sweet from the fruit alone.',
    basePrice: 380,
    base: n(200, 11, 30, 4, 27),
    fibreG: 2,
    badge: 'calculated',
    ingredients: [
      { name: 'Low-fat yogurt', grams: 250 },
      { name: 'Mango', grams: 100 },
    ],
    allergens: ['milk'],
    kitchenAlsoHandles: ['wheat', 'egg', 'soy', 'peanut', 'tree_nut', 'sesame'],
    dietTags: ['vegetarian', 'eggless', 'no_added_sugar'],
    available: true,
    modifierGroups: [
      {
        id: 'addons',
        name: 'Add-ons',
        type: 'multi',
        max: 1,
        options: [
          {
            id: 'chia',
            name: 'Chia seeds (10g)',
            delta: n(49, 1.7, 4, 3, 0),
            priceDelta: 80,
            available: true,
          },
        ],
      },
    ],
  },
  {
    id: 'mint-lemonade',
    storeId: SAMPLE_STORE_ID,
    name: 'Mint Lemonade, No Sugar',
    category: 'drinks',
    description: 'Fresh lime, mint and a pinch of black salt.',
    basePrice: 250,
    base: n(35, 0, 9, 0, 6),
    fibreG: 0,
    badge: 'verified',
    ingredients: [
      { name: 'Fresh lime juice', grams: 40 },
      { name: 'Mint', grams: 5 },
      { name: 'Chilled water', grams: 300 },
    ],
    allergens: [],
    kitchenAlsoHandles: ['milk', 'wheat', 'egg', 'soy', 'peanut', 'tree_nut', 'sesame'],
    dietTags: ['vegetarian', 'eggless', 'dairy_free', 'no_added_sugar'],
    available: true,
    modifierGroups: [SWEETNESS],
  },
  {
    id: 'roasted-chana',
    storeId: SAMPLE_STORE_ID,
    name: 'Roasted Chana Cup',
    category: 'snacks',
    description: 'Crunchy roasted chickpeas with chaat masala. 30g.',
    basePrice: 180,
    base: n(100, 6, 14, 2, 1),
    fibreG: 5,
    badge: 'verified',
    ingredients: [{ name: 'Roasted chickpeas', grams: 30 }],
    allergens: [],
    kitchenAlsoHandles: ['milk', 'wheat', 'egg', 'soy', 'peanut', 'tree_nut', 'sesame'],
    dietTags: ['vegetarian', 'eggless', 'dairy_free', 'no_added_sugar'],
    available: true,
    modifierGroups: [],
  },
];

export function getMenu(): MenuItem[] {
  return SAMPLE_MENU;
}

export function findMenuItem(id: string): MenuItem | undefined {
  return SAMPLE_MENU.find((item) => item.id === id);
}
